### ISSUE TITLE
Category sytem not correct

### ISSUE THREAD

**Issue by airon90** [DavidBerdik/Let-Me-Downgrade#3]
On F-Droid the app is listed in the "sytem" category. Please fix this typo

**Comment by DavidBerdik** [comment]
Thanks for letting me know! As far as I am aware, I can't fix the typo myself. I believe @IzzySoft can though.

**Comment by IzzySoft** [comment]
Correct. Fixed, will show up correctly with the next sync in about 20h from now. Thanks for reporting!

**Comment by DavidBerdik** [comment]
Cool, thanks! Since the issue seems to be resolved (or will be in about 20 hours!), I am going to close this now.
