### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [DavidBerdik/Let-Me-Downgrade#6]
...as  libxposed not yet in ([trusted](https://gitlab.com/fdroid/fdroidserver/-/blob/2a60f6c195dfd24149617ceb1df1731fb3bf50c8/fdroidserver/scanner.py#L452-L471)) maven repos

ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/5300316795#L476

ref: https://github.com/LSPosed/LSPosed/wiki/Develop-Xposed-Modules-Using-Modern-Xposed-API/a7f346f7ec01ea698e1b187fc20de5fc727b0d09#early-access

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/9939b5e937d6d464c4b3cf0a27e7a97c39452218

**Comment by DavidBerdik** [comment]
Please see [here](https://github.com/DavidBerdik/MACsposed/issues/8#issuecomment-1773937982) for my comment on this issue.

**Comment by DavidBerdik** [comment]
@licaon-kter In light of the solution for building for F-Droid that was set up for [CaptureSposed](https://gitlab.com/fdroid/rfp/-/issues/2755), I was wondering if we could revisit this. What are your thoughts? I would really like to get the latest build of Let Me Downgrade on F-Droid. The current version that it is distributing is extremely outdated!

**Comment by licaon-kter** [comment]
Sure, you're gonna use submodules here too?

**Comment by DavidBerdik** [comment]
Yup! I just added them to the repo [here](https://github.com/DavidBerdik/Let-Me-Downgrade/tree/master/libxposed).

**Comment by licaon-kter** [comment]
great, now, libxposed needs Java21, but this app uses 17, right? I mean I've tried  :smile: 

so you need to update some more code

**Comment by DavidBerdik** [comment]
Yes, certainly! I am going to do a new build either later today or tomorrow to resolve this. I'll get back to you once it's done.

**Comment by DavidBerdik** [comment]
@licaon-kter Sorry for the delay. As usual, the wonderful app review team at Google was giving me the runaround with publishing the new version, and to reduce the workload on myself, I wanted to wait until I finally got through the review process before making the release available through other channels. Now that it's done, feel free to proceed with whatever you must do!

**Comment by licaon-kter** [comment]
and we're back: https://gitlab.com/fdroid/fdroiddata/-/commit/308fed650807f399f0a41efbb5dd5cfd3d69a4ca :tada:

**Comment by DavidBerdik** [comment]
@licaon-kter Thank you for fixing this! I am (im)patiently waiting for the new build to hit F-Droid.

**Comment by IzzySoft** [comment]
Thanks from my end too, @DavidBerdik – those details were really helpful! And congrats, [your app](https://apt.izzysoft.de/fdroid/index/apk/com.berdik.letmedowngrade)'s build is reproducible and marked such at IzzyOnDroid – see the green shield next to the version of the latest release in the "Packages" section:

![image](https://github.com/user-attachments/assets/f4705843-4057-4168-bba8-73355d2157c3)

Seeing the `DEPENDENCY_INFO_BLOCK`: that can be easily avoided with a minor addition to your `app/build.gradle.kts`:

```gradle
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}
```

For some background: that BLOB is supposed to be just a binary representation of your app's dependency tree. But as it's encrypted with a public key belonging to Google, only Google can read it – and nobody else can even verify what it really contains. More details can be found e.g. here: [Ramping up security: additional APK checks are in place with the IzzyOnDroid repo](https://android.izzysoft.de/articles/named/iod-scan-apkchecks#blobs).

Having that in would make it perfect :smiley: So thanks in advance for considering it!

**Comment by DavidBerdik** [comment]
@IzzySoft Thanks for handling this for me! I will be glad to make the Gradle change for the next release. I created issue #9 to track this so I will not forget it.

**Comment by IzzySoft** [comment]
Wonderful, thanks!

**Comment by DavidBerdik** [comment]
You're welcome! 😁
