### ISSUE TITLE
Android 14, still not working

### ISSUE THREAD

**Issue by Applewubs** [DavidBerdik/Let-Me-Downgrade#8]
I'm on A14 Aosp with 0 modifications, seems like the lsposed doesn't work, it keeps blocking downgrades no matter the app.

**Comment by DavidBerdik** [comment]
Are you sure that you have turned on the App Downgrades hook through the Quick Settings tile?

![image](https://github.com/DavidBerdik/Let-Me-Downgrade/assets/7663225/b4628bc7-6577-47b0-afb4-975209477c03)

**Comment by gentano** [comment]
he is just talking about non working lsposed.. which has nothing to do with LMD

@Applewubs: try this mod:

https://github.com/mywalkb/LSPosed_mod/releases

**Comment by DavidBerdik** [comment]
@gentano Oh, yes, good point! I had forgotten that the official LSPosed release is having issues on newer updates. With that in mind, I am going to close this.

@Applewubs If using the modded version of LSPosed does not fix the issue, please let me know and I will reopen this.

**Comment by Applewubs** [comment]
> Are you sure that you have turned on the App Downgrades hook through the Quick Settings tile?
> 
> ![image](https://private-user-images.githubusercontent.com/7663225/342876695-b4628bc7-6577-47b0-afb4-975209477c03.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwMTIzOTUsIm5iZiI6MTcyMjAxMjA5NSwicGF0aCI6Ii83NjYzMjI1LzM0Mjg3NjY5NS1iNDYyOGJjNy02NTc3LTQ3YjAtYWZiNC05NzUyMDk0NzdjMDMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjZUMTY0MTM1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2VlYTFjYmJkMTY5ZGIyNTVlZTlhZmI2Y2ExMzY0ZmJhNmU2MzZlM2MwZjQ5NzQ2MGI1MjU5NjdjYjJlYWE2NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.P8Sl-tKWabS8iq9iK9ntjKC8dc_itz86NNT-HNDw0eU)

@DavidBerdik  I'm so so sorry for the late answer, I got quite busy 
Yes I have did had it enabled, I'll try the mod @gentano  recommended, I've not had any problem with any other module so I thought the problem was directly with LMD, anyways thanks for all the answers!

**Comment by DavidBerdik** [comment]
@Applewubs No problem! I understand. Good luck!
